# ===================================================================
# CONFIGURATION POUR LE SERVICE : api-gateway
# Basée sur votre configuration qui fonctionnait
# ===================================================================

# Port d'entrée de toute l'application
server:
  port: 8080

# Configuration des routes de la passerelle
spring:
  cloud:
    gateway:
      routes:
        # 1. Route pour le User Service
        - id: user-service-route
          uri: lb://user-service    # lb://user-service -> trouve le service via Eureka
          predicates:
            # IMPORTANT : Votre nouveau service expose les URLs sur /auth/**
            # et non /api/users/**. Nous utilisons donc le bon chemin.
            - Path=/auth/**

        # Vous pouvez déjà préparer les routes pour vos futurs services ici
        # - id: inventory-service-route
        #   uri: lb://inventory-service
        #   predicates:
        #     - Path=/api/inventory/**
        
        # - id: order-service-route
        #   uri: lb://order-service
        #   predicates:
        #     - Path=/api/orders/**

# NOTE : Le filtre "StripPrefix=1" de votre ancienne configuration servait à retirer "/api"
# avant de transmettre la requête. Comme notre nouvelle route "/auth/**" n'a pas de préfixe
# à retirer, ce filtre n'est plus nécessaire pour cette route spécifique.
