# ===================================================================
# CONFIGURATION POUR LE SERVICE : user-service
# ===================================================================

# Port sur lequel ce service spécifique va démarrer
server:
  port: 8081

# Configuration de la base de données H2 en mémoire
spring:
  datasource:
    url: jdbc:h2:mem:userdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: update 
  h2:
    console:
      enabled: true
      path: /h2-console

# Propriété métier : la clé secrète pour les tokens JWT
jwt:
  secret: MaSuperCleSecreteAssezLonguePourEtreSureEtGereeViaGit
